### ISSUE TITLE
[ISSUE] Array Reference 

### ISSUE THREAD

**Issue by XenoCraftMC** [silvia-odwyer/Onyx#1]
In your [Bitcoin](https://github.com/silvia-odwyer/Onyx/blob/master/commands/search/bitcoin.js) command at lines [35](https://github.com/silvia-odwyer/Onyx/blob/master/commands/search/bitcoin.js#L35) and [36](https://github.com/silvia-odwyer/Onyx/blob/master/commands/search/bitcoin.js#L36) you have referenced to the wrong indices in the results array (Arrays start from `0`).
Currently, it outputs [this](http://prntscr.com/ljqw1i). With [this correction](https://hastebin.com/awabeqikir.cs), it outputs [this](http://prntscr.com/ljqwcz).

**Comment by silvia-odwyer** [comment]
Thanks for alerting me to this; I've fixed the bug, and it's outputting the results now as per normal. 

I really appreciate you taking the time to submit this PR, and for submitting your proposed changes as well, so many thanks! 

Oh, I'll be adding more crypto commands in the future, so keep an eye out for those. 👀 

Thanks again, @XenoCraftMC!
