### ISSUE TITLE
Installation issues?

### ISSUE THREAD

**Issue by 503geek** [silvia-odwyer/Onyx#6]
I'm getting two errors - there could be more, these are just with some commands I've tried. But many commands are working as expected, fwiw.

Error on running `emojify` 

`TypeError: Cannot read property 'length' of undefined`

Maybe from https://github.com/silvia-odwyer/Onyx/blob/8739a367047b746c90b84ea249a80fb14aba8018/commands/message_formatting/emojify.js#L35 ?

Error on running `old-define`

`Error: Cannot find module './assets/dictionary.json'`

That was interesting to me since the path is not `../../assets` like you have it in your code, but I don't know how Discord deals with pathing when the bot is added by invite (I have not built the bot myself, these issues are after inviting it to my server).

Let me know if there's any other info I can provide.

**Comment by silvia-odwyer** [comment]
Hi @503geek Thanks for opening this issue! 😄 👍 I'm in the process of updating all commands, and the full upsate should be completed quite soon. 

The commands you mentioned will all be working then, but if you notice any other bugs, it would be great if you could open another issue, thanks!

**Comment by silvia-odwyer** [comment]
Since the issues are now fixed, I'm going to close this. ✅
